language: haskell
script: "make ci"

ghc:
  - "7.10"
  - "7.8"
  - "7.6"
  - "7.4"

before_install:
  - cabal update
  - cabal install cabal-install
  - cabal sandbox init
  - export PATH=~/.cabal/bin:$PATH
  - for i in `cat REPOS`; do git clone http://github.com/haskell-distributed/$i ; done
  - for i in `cat REPOS`; do cabal sandbox add-source $i ; done

install:
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests
  - cabal test --show-details=always
